ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('store.urls'))
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import StoreView, DetailsView, cart, remove_cart, OrderView, remove_single_product, Checkout, PaymentView, CategoryView, ProfileView


urlpatterns = [
    # Leave as empty string for base url
    path('', StoreView.as_view(), name="store"),
    path('details/<slug>', DetailsView.as_view(), name="details"),
    path('category/<category>', CategoryView.as_view(), name='category'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('cart/<slug>', cart, name='cart'),
    path('remove_cart/<slug>', remove_cart, name='remove_cart'),
    path('remove_single_product/<slug>/',
         remove_single_product, name='remove_single_product'),
    path('orderview/', OrderView.as_view(), name='orderview'),
    path('checkout/', Checkout.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),

]

store/models.py
from django.db import models
from django.db.models.signals import post_save
from django.db.models import Sum
from django.conf import settings
from django.shortcuts import reverse
from django_countries.fields import CountryField
# Create your models here.

CATEGORY_CHOICES = (
    ('groceries', 'Groceries'),
    ('household', 'Household'),
    ('personal care', 'Personal Care'),
    ('packaged foods', 'Packaged Foods'),
    ('Beverages', 'beverages')
)

AVAILABILITY_PRODUCT = (
    ('S', 'In Stock'),
    ('0', 'Out Of Range')
)
ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=20)
    availabily = models.CharField(
        choices=AVAILABILITY_PRODUCT, max_length=1, blank=True, null=True)
    description = models.TextField()
    slug = models.SlugField()
    image = models.ImageField()

    def __str__(self):
        return self.name

    def get_url(self):
        return reverse("details", kwargs={
            'slug': self.slug
        })

    def get_cart_url(self):
        return reverse("cart", kwargs={
            'slug': self.slug
        })

    def get_remove_cart_url(self):
        return reverse("remove-cart", kwargs={
            'slug': self.slug
        })


class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.product.name}"

    def get_total_price(self):
        return self.quantity * self.product.price

    def get_total_discount_price(self):
        return self.quantity * self.product.discount_price

    def get_amount_saved(self):
        return self.get_total_price() - self.get_total_discount_price()

    def get_final_price(self):
        if self.product.discount_price:
            return self.get_total_discount_price()
        return self.get_total_price()


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'
class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    products = models.ManyToManyField(OrderItem, blank=True)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.CASCADE, default=None, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.CASCADE, default=None, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.CASCADE, default=None, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.products.all():
            total += order_item.get_final_price()

        return total




class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

store/forms.py
from django import forms
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget


PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'PayPal')
)


class CheckoutForm(forms.Form):
    shipping_address = forms.CharField(required=False)
    shipping_address2 = forms.CharField(required=False)
    shipping_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    shipping_zip = forms.CharField(required=False)

    billing_address = forms.CharField(required=False)
    billing_address2 = forms.CharField(required=False)
    billing_country = CountryField(blank_label='(select country)').formfield(
        required=False,
        widget=CountrySelectWidget(attrs={
            'class': 'custom-select d-block w-100',
        }))
    billing_zip = forms.CharField(required=False)

    same_billing_address = forms.BooleanField(required=False)
    set_default_shipping = forms.BooleanField(required=False)
    use_default_shipping = forms.BooleanField(required=False)
    set_default_billing = forms.BooleanField(required=False)
    use_default_billing = forms.BooleanField(required=False)

    payment_option = forms.ChoiceField(
        widget=forms.RadioSelect, choices=PAYMENT_CHOICES)


class PaymentForm(forms.Form):
    stripeToken = forms.CharField(required=False)
    save = forms.BooleanField(required=False)
    use_default = forms.BooleanField(required=False)

store/views.py
import random
import string
from django.shortcuts import render, get_object_or_404, redirect
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils import timezone
from .models import Product, OrderItem, Order, Address, Payment, UserProfile
from django.views.generic import ListView, DetailView, View
from django.core.exceptions import ObjectDoesNotExist
from store.forms import CheckoutForm, PaymentForm
import stripe
stripe.api_key = 'sk_test_51HrlwSAijGs9vADEUzvrkuAAglcTEoVC1q3gL3sCdZHM4WHyfyqAbpeLmvng52vC2C4hAtzEZn565YiHGq2x1F4v00oYlYzmZ0'
# Create your views here.


def products(request):
    context = {
        'products': Product.objects.all()
    }
    return render(request, "details.html", context)


class StoreView(ListView):
    model = Product
    template_name = "store.html"


class DetailsView(DetailView):
    model = Product
    template_name = "details.html"


class CategoryView(ListView):
    model = Product
    template_name = 'category.html'

    def get_queryset(self):
        category = self.kwargs.get('category')
        return Product.objects.filter(category=category)


class ProfileView(View):
    def get(self, *args, **kwargs):

        orders = Order.objects.filter(
            user=self.request.user, ordered=True)

        context = {
            "orders": orders,


        }
        return render(self.request, "profile.html", context)


class OrderView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            context = {
                'object': order
            }
            return render(self.request, 'orderview.html', context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("/")


@login_required
def cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        product=product,
        user=request.user,
        ordered=False
    )
    order_qs = Order.objects.filter(user=request.user, ordered=False)
    if order_qs.exists():
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
            messages.info(request, "This product quantity was updated.")
            return redirect("orderview")
        else:
            order.products.add(order_item)
            messages.info(request, "This product was added to your cart.")
            return redirect("orderview")
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(
            user=request.user, ordered_date=ordered_date)
        order.products.add(order_item)
        messages.info(request, "This product was added to your cart.")
        return redirect("orderview")


@login_required
def remove_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            order.products.remove(order_item)
            order_item.delete()
            messages.info(request, "This product was removed from your cart.")
            return redirect("orderview")
        else:
            messages.info(request, "This product was not in your cart")
            return redirect("details", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("details", slug=slug)


@login_required
def remove_single_product(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(
        user=request.user,
        ordered=False
    )
    if order_qs.exists():
        order = order_qs[0]
        # check if the order product is in the order
        if order.products.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product,
                user=request.user,
                ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.products.remove(order_item)
            messages.info(request, "This product quantity was updated.")
            return redirect("orderview")
        else:
            messages.info(request, "This product was not in your cart")
            return redirect("details", slug=slug)
    else:
        messages.info(request, "You do not have an active order")
        return redirect("details", slug=slug)


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid


class Checkout(View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'order': order,
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update(
                    {'default_billing_address': billing_address_qs[0]})
            return render(self.request, "checkout.html", context)
        except ObjectDoesNotExist:
            messages.info(self.request, "You do not have an active order")
            return redirect("checkout")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    print("Using the defualt shipping address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default shipping address available")
                        return redirect('checkout')
                else:
                    print("User is entering a new shipping address")
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.user,
                            street_address=shipping_address1,
                            apartment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                            address_type='S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required shipping address fields")

                use_default_billing = form.cleaned_data.get(
                    'use_default_billing')
                same_billing_address = form.cleaned_data.get(
                    'same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print("Using the defualt billing address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='B',
                        default=True

store/templates/category.html
{% extends "base.html"%} {% block title %}
<title>Category</title>
{% endblock %} {% block content %} {% load static %}


<!--Products Section: Block Content-->
<section>
    <div class="">
        <!-- Grid row -->
        <div class="row mt-5 mb-5 mr-5 ml-5">
            {% for product in object_list %}
            <!-- Grid column -->
            <div class="col-md-3 mb-3">
                <!-- Card -->
                <div class="">
                    <div class="view zoom overlay z-depth-2 rounded">
                        <img class="img-fluid w-100" src="{{product.image.url}}" alt="Sample" />
                        <a href="#!">
                            <div class="mask">
                                <img class="img-fluid w-100" src="{{product.image.url}}" />
                                <div class="mask rgba-black-slight"></div>
                            </div>
                        </a>
                    </div>

                    <div class="text-center pt-4">
                        <h5>{{product.name}}</h5>
                        <span class="badge badge-pill blue">{{ product.get_availabily_display }}</span>

                        <hr />
                        {% if product.discount_price %}
                        <h6 class="mb-3"><del>${{product.price}}</del></h6>
                        <h6 class="mb-3"> ${{ product.discount_price  }}</h6>

                        {%else %}

                        <h6 class="mb-3">${{product.price}}</h6>

                        {% endif %}

                        <a href="{{product.get_cart_url}}" type="button"
                            class="btn btn-primary btn-sm mr-1 mb-2 update-cart">
                            <i class="fas fa-shopping-cart pr-2 update-cart"></i>Add to cart
                        </a>
                        <a href="{{product.get_url}}" type="button" class="btn btn-light btn-sm mr-1 mb-2 view-item"><i
                                class="fas fa-info-circle pr-2"></i>Details</a>
                    </div>
                </div>
                <!-- Card -->
            </div>
            <!-- Grid column -->
            {% endfor %}
        </div>
        <!-- Grid row -->
    </div>
</section>
<!--Section: Block Content-->
{% endblock %}

store/templates/details.html
{% extends "base.html"%}
{% block title %}
<title>details</title>
{% endblock %}

{% block content %}
{% load static %}
<!--Main layout-->
<main class="pt-2">
    <div class=" dark-grey-text mt-5 ml-5">

        <!--Grid row-->
        <div class="row wow fadeIn">

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <img src="{{object.image.url}}" class="img-fluid" alt="">

            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-6 mb-4">

                <!--Content-->


                <div class="p-4">
                    <h2 class="mb-4">{{object.name}}</h2>

                    <div class="mb-3">
                        <a href="">
                            <span class="badge purple mr-1">{{object.get_category_display}}</span>
                        </a>

                        <span class="badge blue mr-1">{{ object.get_availabily_display }}</span>

                    </div>

                    <p class="lead">

                        {% if object.discount_price %}
                        <span class="mr-1">
                            <del>
                                {{ object.price  }}
                            </del>
                        </span>
                        <span>${{ object.discount_price }}</span>
                        {% else %}

                        <span>${{ object.price }}</span>

                        {% endif %}

                    </p>

                    <p class="lead font-weight-bold">Description</p>

                    <p>{{ object.description }}</p>


                    <a href="{{ object.get_cart_url }}" class="btn btn-primary btn-md my-0 p">
                        Add to cart
                        <i class="fas fa-shopping-cart ml-1"></i>
                    </a>
                    <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
                        Remove from cart
                    </a>
                </div>

                <!--Content-->

            </div>
            <!--Grid column-->

        </div>
        <div class="clear-fix"></div>
        <!--Grid row-->
    </div>
    {% endblock %}

store/templates/orderitems.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
        <span class="text-muted">Your cart</span>
        <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
        {% for order_item in order.products.all %}
        <li class="list-group-item d-flex justify-content-between lh-condensed">
            <div>
                <h6 class="my-0">{{ order_item.quantity }} x {{ order_item.product.name}}</h6>
                <small class="text-muted">{{ order_item.item.description}}</small>
            </div>
            <span class="text-muted">${{ order_item.get_final_price }}</span>
        </li>
        {% endfor %}
        <li class="list-group-item d-flex justify-content-between">
            <span>Total (USD)</span>
            <strong>${{ order.get_total }}</strong>
        </li>
    </ul>

</div>

store/templates/orderview.html
{% extends "base.html" %}

{% block content %}
<main>
  <div class="container">

    <div class="table-responsive text-nowrap">
      <h2>Order Summary</h2>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Product title</th>
            <th scope="col">Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Total Item Price</th>
          </tr>
        </thead>
        <tbody>
          {% for order_item in object.products.all %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order_item.product.name }}</td>
            <td>{{ order_item.product.price }}</td>
            <td>
              <a href="{% url 'remove_single_product' order_item.product.slug %}"><i class="fas fa-minus mr-2"></i></a>
              {{ order_item.quantity }}
              <a href="{% url 'cart' order_item.product.slug %}"><i class="fas fa-plus ml-2"></i></a>
            </td>
            <td>
              {% if order_item.product.discount_price %}
              ${{ order_item.get_total_discount_price }}
              <span class="badge badge-primary">Saving ${{ order_item.get_amount_saved }}</span>
              {% else %}
              ${{ order_item.get_total_price }}
              {% endif %}
              <a style='color: red;' href="{% url 'remove_cart' order_item.product.slug %}">
                <i class="fas fa-trash float-right"></i>
              </a>
            </td>
          </tr>
          {% empty %}
          <tr>
            <td colspan='5'>Your cart is empty</td>
          </tr>
          <tr>
            <td colspan="5">
              <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
          </tr>
          {% endfor %}
          {% if object.coupon %}
          <tr>
            <td colspan="4"><b>Coupon</b></td>
            <td><b>-${{ object.coupon.amount }}</b></td>
          </tr>
          {% endif %}
          {% if object.get_total %}
          <tr>
            <td colspan="4"><b>Order Total</b></td>
            <td><b>${{ object.get_total }}</b></td>
          </tr>
          <tr>
            <td colspan="5">
              <a class='btn btn-warning float-right ml-2' href="{% url 'checkout' %}">Proceed to checkout</a>
              <a class='btn btn-primary float-right' href='/'>Continue shopping</a>
            </td>
          </tr>
          {% endif %}
        </tbody>
      </table>

    </div>

  </div>
</main>

{% endblock content %}

store/templates/store.html
{% extends "base.html"%} {% block title %}
<title>home page</title>
{% endblock %} {% block content %} {% load static %}

<!--/.Slider -->
<div class="">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/slider1.jpg'%}" alt="First slide" />
        <div class="carousel-caption d-none d-md-block">
          <h3>BUY RICE PRODUCTS</h3>
          <p class="text-white">ARE NOW ON LINE WITH US</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/slider2.jpg'%}" alt="Second slide" />
        <div class="carousel-caption d-none d-md-block">
          <h3>WHOLE SPICES PRODUCTS</h3>
          <p class="text-white">ARE NOW ON LINE WITH US</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/slider3.jpg'%}" alt="Third slide" />
        <div class="carousel-caption d-none d-md-block">
          <h3>WE ARE ON SALE!!</h3>
          <p class="text-white">BUY GOODS</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="clearfix"></div>
</div>
<!--/.Slider -->

<!--Products Section: Block Content-->
<section>
  <div class="">
    <!-- Grid row -->
    <div class="row mt-5 mb-5 mr-5 ml-5">
      {% for product in object_list %}
      <!-- Grid column -->
      <div class="col-md-3 mb-3">
        <!-- Card -->
        <div class="">
          <div class="view zoom overlay z-depth-2 rounded">
            <img class="img-fluid w-100" src="{{product.image.url}}" alt="Sample" />
            <a href="#!">
              <div class="mask">
                <img class="img-fluid w-100" src="{{product.image.url}}" />
                <div class="mask rgba-black-slight"></div>
              </div>
            </a>
          </div>

          <div class="text-center pt-4">
            <h5>{{product.name}}</h5>
            <span class="badge badge-pill blue">{{ product.get_availabily_display }}</span>

            <hr />
            {% if product.discount_price %}
            <h6 class="mb-3"><del>${{product.price}}</del></h6>
            <h6 class="mb-3"> ${{ product.discount_price  }}</h6>

            {%else %}

            <h6 class="mb-3">${{product.price}}</h6>

            {% endif %}

            <a href="{{product.get_cart_url}}" type="button" class="btn btn-primary btn-sm mr-1 mb-2 update-cart">
              <i class="fas fa-shopping-cart pr-2 update-cart"></i>Add to cart
            </a>
            <a href="{{product.get_url}}" type="button" class="btn btn-light btn-sm mr-1 mb-2 view-item"><i
                class="fas fa-info-circle pr-2"></i>Details</a>
          </div>
        </div>
        <!-- Card -->
      </div>
      <!-- Grid column -->
      {% endfor %}
    </div>
    <!-- Grid row -->
  </div>
</section>
<!--Section: Block Content-->

<!--/.Slider 2 -->
<div class="">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class="d-block w-100" src="{% static 'images/b1.jpg'%}" alt="First slide" />
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="{% static 'images/b2.jpg'%}" alt="Second slide" />
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <div class="clearfix"></div>
</div>
<!--/.Slider 2-->

{% endblock %}